source "https://rubygems.org"

# gem "github-pages", group: :jekyll_plugins

gem "jekyll", "3.9.0"

group :github_pages_compatible do
    gem "json", "~> 2.3", ">= 2.3.0"
    gem "coffee-script", "~> 2.4"
    gem "coffee-script-source", "~> 1.12"
    gem "ethon", "~> 0.10"
    gem "execjs", "~> 2.7"
    gem "minima", "~> 2.5", ">= 2.5.1"
    gem "terminal-table", "~> 1.4"
    gem "unicode-display_width", "~> 1.1"
end

group :jekyll_plugins do
   gem "jekyll-feed", "~> 0.11", ">= 0.11.0"
   gem "jekyll-sitemap", ">= 1.2.0"
   gem "jekyll-gist", ">= 1.5.0"
   gem "jekyll-paginate", "1.1.0"
   gem "jekyll-seo-tag", ">= 2.6.1"
   gem "jekyll-avatar", "~> 0.7", ">= 0.7.0"
   gem "jekyll-coffeescript", "~> 1.0"
   gem "jekyll-default-layout", "~> 0.1", ">= 0.1.4"
   gem "jekyll-github-metadata", "~> 2.13", ">= 2.13.0"
   gem "jekyll-optional-front-matter", "~> 0.3", ">= 0.3.2"
   gem "jekyll-readme-index", "0.0.3"
   gem "jekyll-redirect-from", "~> 0.16", ">= 0.16.0"
   gem "jekyll-relative-links", "~> 0.5.3"
   gem "jekyll-swiss", "~> 0.4"
   gem "jekyll-theme-architect", "0.0.3"
   gem "jekyll-theme-cayman", "0.0.3"
   gem "jekyll-theme-dinky", "0.0.3"
   gem "jekyll-theme-hacker", "0.0.3"
   gem "jekyll-theme-leap-day", "0.0.3"
   gem "jekyll-theme-merlot", "0.0.3"
   gem "jekyll-theme-midnight", "0.0.3"
   gem "jekyll-theme-minimal", "0.0.3"
   gem "jekyll-theme-modernist", "0.0.3"
   gem "jekyll-theme-primer", "~> 0.5", ">= 0.5.4"
   gem "jekyll-theme-slate", "0.0.3"
   gem "jekyll-theme-tactile", "0.0.3"
   gem "jekyll-theme-time-machine", "0.0.3"
   gem "jekyll-titles-from-headings", "~> 0.5", ">= 0.5.3"
   gem "jekyll-include-cache", "~> 0.1", ">= 0.1.0"
   gem 'jekyll-youtube', '~> 1.0', '>= 1.0.0'
end

gem "kramdown", "~> 2.3", ">= 2.3.1"
gem "rouge", "~> 2.0"
gem "pry"

gem "public_suffix", "~> 3.0"
